'use client'

import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import {Inter} from 'next/font/google'
import {current_version, site_title} from '@/config/global';
import Navigator from '@/components/layout/widget/navibar/navigator';
import React from 'react';
import {FloatButton} from 'antd';
import ClearLocalStorageButton from "@/components/button/clear_local_storage_button";
import {WaterMark} from "@ant-design/pro-components";
import {GlobalContextProvider} from "@/components/providers/global_context_provider";

const inter = Inter({subsets: ['latin']})


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({children, side}) {

    return (
        <html lang="en">
        <head>
            <link href="https://cdn.staticfile.org/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet"/>
            <link href="https://cdn.staticfile.net/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css"
                  rel="stylesheet"/>
            <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.3/js/bootstrap.min.js" async></script>
            <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js" async></script>
            <title></title>

        </head>

        <body className={inter.className}>
        <GlobalContextProvider>
            <WaterMark content={site_title}>
                <header>
                    <Navigator/>
                </header>
                <main style={{marginTop: '100px'}}>
                    <div id="basic-container" className="container-fluid">
                        <div id="body-container" className="row m-3 il-round-border p-2 pt-3" style={{'height': '100%'}}>
                            {children}
                        </div>
                        {/* <FloatButton onClick={onBackToTop} /> */}
                        <FloatButton.Group shape="circle">
                        <ClearLocalStorageButton/>
                        <FloatButton.BackTop tooltip={"返回页面顶部"}/>
                        </FloatButton.Group>
                    </div>
                </main>
                <footer>
                    <div id="footer-container" className="container-fluid">
                        <div id="footer" className="container-fluid">
                            <div id="copyright" className="d-flex justify-content-center">
                                <div className={"align-content-center align-self-center align"}>
                                <p>Copyright © 2022-2024 {site_title}. Made with ❤ by Jacky_Blackson. All rights
                                    reserved.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </WaterMark>
        </GlobalContextProvider>
        </body>

        </html>
    )
}